apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-kaniko
spec:
  serviceAccountName: kaniko-ksa

  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      command:
        - /busybox/sh
      args:
        - -c
        - sleep 999999
      tty: true

    - name: kubectl
      image: google/cloud-sdk:latest
      command:
        - /bin/sh
      args:
        - -c
        - sleep 999999
      tty: true